default:
  config:
    path: shared-config.yaml
# Use the config with 'devspace use config dev-service1'
dev-service1:
  config:
    path: shared-config.yaml
  # Overrides defined overridden fields in the original config
  # You can specify multiple overrides which are applied in the order
  # you specify them. Array types are completely overriden and maps will be merged
  overrides:
    - data:
        dev:
          overrideImages:
            - name: service-image-1
              entrypoint:
                - sleep
                - "9999999999"
          terminal:
            labelSelector:
              app.kubernetes.io/component: service-1
          ports:
            - labelSelector:
                app.kubernetes.io/component: service-1
              forward:
                - port: 8080
          sync:
            - labelSelector:
                app.kubernetes.io/component: service-1
              localSubPath: ./service1
# Use the config with 'devspace use config dev-service2'
dev-service2:
  config:
    path: shared-config.yaml
  overrides:
    - data:
        dev:
          overrideImages:
            - name: service-image-2
              entrypoint:
                - sleep
                - "9999999999"
          terminal:
            labelSelector:
              app.kubernetes.io/component: service-2
          ports:
            - labelSelector:
                app.kubernetes.io/component: service-2
              forward:
                - port: 8080
          sync:
            - labelSelector:
                app.kubernetes.io/component: service-2
              localSubPath: ./service2
