version: v1beta2
images:
  service-image-1:
    image: service-1
    dockerfile: service1/Dockerfile
    context: service1/
    build:
      docker:
        skipPush: true
  service-image-2:
    image: service-2
    dockerfile: service2/Dockerfile
    context: service2/
    build:
      docker:
        skipPush: true
deployments:
  - name: service-1
    component:
      containers:
        - image: service-1
  - name: service-2
    component:
      containers:
        - image: service-2
cluster:
  kubeContext: minikube
  namespace: devspace
