apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: default
    spec:
      containers:
      - name: default
        image: devspace
