apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devspace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: default
        app.kubernetes.io/name: devspace-app
    spec:
      containers:
        - name: default
          # The correct image tag will be inserted during devspace dev / devspace deploy
          image: devspace
