version: v1alpha3
#cluster:
 # kubeContext: minikube
dev:
  overrideImages:
  - name: default
    entrypoint:
    - sleep
    - "999999999999"
  ports:
  - portMappings:
    - localPort: 3000
      remotePort: 3000
    selector: default
  selectors:
  - name: default
    labelSelector:
      app.kubernetes.io/component: default
      app.kubernetes.io/name: devspace-app
  sync:
  - containerPath: /app
    localSubPath: ./
    selector: default
    uploadExcludePaths:
    - Dockerfile
    - .devspace/
    - chart/
    - node_modules/
images:
  default:
    createPullSecret: true
    image: dscr.io/yourusername/devspace
deployments:
- name: devspace-app
  helm:
    chartPath: ./chart
