version: v1alpha2
cluster:
  kubeContext: minikube
  namespace: devspace
deployments:
- helm:
    chartPath: ./chart
  name: devspace-app
dev:
  overrideImages:
  - entrypoint:
    - sleep
    - "999999999999"
    name: default
  ports:
  - portMappings:
    - localPort: 3000
      remotePort: 3000
    selector: default
  selectors:
  - labelSelector:
      app.kubernetes.io/component: default
      app.kubernetes.io/name: devspace-app
    name: default
  sync:
  - containerPath: /app
    localSubPath: ./
    selector: default
    uploadExcludePaths:
    - Dockerfile
    - .devspace/
    - chart/
    - node_modules/
images:
  default:
    image: devspace
    skipPush: true
