cluster:
  cloudProvider: devspace-cloud
deployments:
- helm:
    chartPath: ./chart
  name: devspace-default
dev:
  autoReload:
    deployments:
    - devspace-default
  ports:
  - portMappings:
    - localPort: 3000
      remotePort: 3000
    selector: default
  selectors:
  - labelSelector:
      devspace: default
    name: default
  sync:
  - containerPath: /app
    localSubPath: ./
    selector: default
    uploadExcludePaths:
    - Dockerfile
    - .devspace/
    - chart/
    - node_modules/
images:
  default:
    createPullSecret: true
    name: test.dscr.io/lukasgentele/devspace
version: v1alpha2
