version: v1alpha2
cluster:
  kubeContext: minikube
  namespace: devspace
deployments:
- name: devspace-node
  kubectl:
    manifests:
    - node/kube/*
- name: devspace-php
  helm:
    chartPath: php/chart
dev:
  overrideImages:
  - name: node
    entrypoint: ["sleep", "9999999999"]
  ports:
  - labelSelector:
      release: devspace-node
    portMappings:
    - localPort: 3000
      remotePort: 3000
  sync:
  - containerPath: /app
    labelSelector:
      release: devspace-node
    localSubPath: ./node
    uploadExcludePaths:
    - Dockerfile
    - kube/
  - containerPath: /var/www/html
    labelSelector:
      release: devspace-php
    localSubPath: ./php
    uploadExcludePaths:
    - Dockerfile
    - chart/
  terminal:
    labelSelector:
      release: devspace-node
images:
  node:
    build:
      contextPath: node/
      dockerfilePath: node/Dockerfile
    image: node
    skipPush: true
  php:
    build:
      contextPath: php/
      dockerfilePath: php/Dockerfile
    image: php
    skipPush: true
