version: v1alpha3
cluster:
  kubeContext: minikube
  namespace: devspace
deployments:
- helm:
    chartPath: ./chart
  name: devspace-default
dev:
  overrideImages:
  - name: default
    entrypoint: ["sleep", "999999999999"]
  ports:
  - selector: default
    portMappings:
    - localPort: 8080
      remotePort: 8080
  selectors:
  - name: default
    labelSelector:
      app.kubernetes.io/component: default
      app.kubernetes.io/name: devspace-default
  sync:
  - containerPath: /app
    selector: default
    localSubPath: ./
    uploadExcludePaths:
    - Dockerfile
    - .devspace/
    - chart/
    - app
images:
  default:
    build:
      kaniko:
        cache: true
    image: yourdockeruser/devspace
