version: v1alpha3
#cluster:
 # kubeContext: minikube
deployments:
- name: devspace-default
  kubectl:
    manifests:
    - kube/*
dev:
  autoReload:
    deployments:
    - devspace-default
    images:
    - default
  overrideImages:
  - name: default
    entrypoint: ["sleep", "99999999999"]
  selectors:
  - name: default
    labelSelector:
      app.kubernetes.io/component: default
      app.kubernetes.io/name: devspace-app
  ports:
  - selector: default
    portMappings:
    - localPort: 3000
      remotePort: 3000
  sync:
  - containerPath: /app
    selector: default
    localSubPath: ./
    uploadExcludePaths:
    - Dockerfile
    - .devspace/
    - chart/
    - vendor/
images:
  default:
    image: dscr.io/yourusername/quickstart
    createPullSecret: true
