version: v1alpha2
cluster:
  cloudProvider: devspace-cloud
 # kubeContext: minikube
deployments:
- helm:
    chartPath: ./chart
  name: devspace-app
dev:
  ports:
  - portMappings:
    - localPort: 8080
      remotePort: 80
    selector: default
  selectors:
  - labelSelector:
      app.kubernetes.io/component: default
      app.kubernetes.io/name: devspace-app
    name: default
  sync:
  - containerPath: /var/www/html
    localSubPath: ./
    selector: default
    uploadExcludePaths:
    - Dockerfile
    - .devspace/
    - chart/
images:
  default:
    createPullSecret: true
    image: dscr.io/fabiankramm/devspace
